services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins-container
    ports:
      - "8080:8080"
    volumes:
      - .:/var/jenkins_home
  tomcat:
    image: tomcat:latest
    ports:
      - 8888:8080
    volumes:
      - .:/usr/local/tomcat/webapps/status
    container_name: tomcat-container
