services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins-container
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - .:/var/jenkins_home
  tomcat:
    image: tomcat:latest
    ports:
      - 8888:8080
    volumes:
      - .:/usr/local/tomcat/webapps
    container_name: tomcat-container
